-- ------------------------------
-- desc: generated by xls2data.py
-- source: 场景加载配置表.xls
-- sheet: 场景加载配置表
-- ------------------------------


Data = {
	['startScene'] = {
		['path'] = '',--'Assets/Scenes/s001/s001.unity',
		['level'] = 'StartScene',
	},
	['coinScene'] = {
		['path'] = '',
		['level'] = 'CoinScene',
	},
	['loginScene'] = {
		['path'] = '',
		['level'] = 'login',
	},
	['battleScene'] = {
		['path'] = '',
		['level'] = 'BattleScene',
	},
	['copyScene'] = {
		['path'] = '',
		['level'] = 'CopyScene',
	},
	['settingScene'] = {
		['path'] = '',
		['level'] = 'SettingScene',
	},	
}
